// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgconn "github.com/jackc/pgx/v5/pgconn"

	pgx "github.com/jackc/pgx/v5"
)

// DBProvider is an autogenerated mock type for the DBProvider type
type DBProvider struct {
	mock.Mock
}

type DBProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *DBProvider) EXPECT() *DBProvider_Expecter {
	return &DBProvider_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *DBProvider) Close() {
	_m.Called()
}

// DBProvider_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DBProvider_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DBProvider_Expecter) Close() *DBProvider_Close_Call {
	return &DBProvider_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DBProvider_Close_Call) Run(run func()) *DBProvider_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBProvider_Close_Call) Return() *DBProvider_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *DBProvider_Close_Call) RunAndReturn(run func()) *DBProvider_Close_Call {
	_c.Run(run)
	return _c
}

// Exec provides a mock function with given fields: ctx, sql, arguments
func (_m *DBProvider) Exec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, arguments...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)); ok {
		return rf(ctx, sql, arguments...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgconn.CommandTag); ok {
		r0 = rf(ctx, sql, arguments...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, sql, arguments...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBProvider_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type DBProvider_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - arguments ...interface{}
func (_e *DBProvider_Expecter) Exec(ctx interface{}, sql interface{}, arguments ...interface{}) *DBProvider_Exec_Call {
	return &DBProvider_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, arguments...)...)}
}

func (_c *DBProvider_Exec_Call) Run(run func(ctx context.Context, sql string, arguments ...interface{})) *DBProvider_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *DBProvider_Exec_Call) Return(_a0 pgconn.CommandTag, _a1 error) *DBProvider_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBProvider_Exec_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (pgconn.CommandTag, error)) *DBProvider_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, sql, args
func (_m *DBProvider) Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (pgx.Rows, error)); ok {
		return rf(ctx, sql, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Rows); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBProvider_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type DBProvider_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *DBProvider_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *DBProvider_Query_Call {
	return &DBProvider_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *DBProvider_Query_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *DBProvider_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *DBProvider_Query_Call) Return(_a0 pgx.Rows, _a1 error) *DBProvider_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBProvider_Query_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (pgx.Rows, error)) *DBProvider_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: ctx, sql, args
func (_m *DBProvider) QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Row); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}

// DBProvider_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type DBProvider_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *DBProvider_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *DBProvider_QueryRow_Call {
	return &DBProvider_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *DBProvider_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *DBProvider_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *DBProvider_QueryRow_Call) Return(_a0 pgx.Row) *DBProvider_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBProvider_QueryRow_Call) RunAndReturn(run func(context.Context, string, ...interface{}) pgx.Row) *DBProvider_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// NewDBProvider creates a new instance of DBProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBProvider {
	mock := &DBProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
