server:
  host: "localhost"
  port: "8080"

redis:
  address: "localhost:6379"
  password: ""

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "explore"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 10

logger:
  level: "info"
  format: "json"
