// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// CacheProvider is an autogenerated mock type for the CacheProvider type
type CacheProvider struct {
	mock.Mock
}

type CacheProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheProvider) EXPECT() *CacheProvider_Expecter {
	return &CacheProvider_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: ctx, keys
func (_m *CacheProvider) Del(ctx context.Context, keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheProvider_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type CacheProvider_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *CacheProvider_Expecter) Del(ctx interface{}, keys ...interface{}) *CacheProvider_Del_Call {
	return &CacheProvider_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *CacheProvider_Del_Call) Run(run func(ctx context.Context, keys ...string)) *CacheProvider_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *CacheProvider_Del_Call) Return(_a0 error) *CacheProvider_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheProvider_Del_Call) RunAndReturn(run func(context.Context, ...string) error) *CacheProvider_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *CacheProvider) Get(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CacheProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CacheProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheProvider_Expecter) Get(ctx interface{}, key interface{}) *CacheProvider_Get_Call {
	return &CacheProvider_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *CacheProvider_Get_Call) Run(run func(ctx context.Context, key string)) *CacheProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CacheProvider_Get_Call) Return(_a0 string, _a1 error) *CacheProvider_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CacheProvider_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *CacheProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetJSON provides a mock function with given fields: ctx, key, out
func (_m *CacheProvider) GetJSON(ctx context.Context, key string, out interface{}) (bool, error) {
	ret := _m.Called(ctx, key, out)

	if len(ret) == 0 {
		panic("no return value specified for GetJSON")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (bool, error)); ok {
		return rf(ctx, key, out)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) bool); ok {
		r0 = rf(ctx, key, out)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, key, out)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CacheProvider_GetJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJSON'
type CacheProvider_GetJSON_Call struct {
	*mock.Call
}

// GetJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - out interface{}
func (_e *CacheProvider_Expecter) GetJSON(ctx interface{}, key interface{}, out interface{}) *CacheProvider_GetJSON_Call {
	return &CacheProvider_GetJSON_Call{Call: _e.mock.On("GetJSON", ctx, key, out)}
}

func (_c *CacheProvider_GetJSON_Call) Run(run func(ctx context.Context, key string, out interface{})) *CacheProvider_GetJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *CacheProvider_GetJSON_Call) Return(_a0 bool, _a1 error) *CacheProvider_GetJSON_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CacheProvider_GetJSON_Call) RunAndReturn(run func(context.Context, string, interface{}) (bool, error)) *CacheProvider_GetJSON_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, expiration
func (_m *CacheProvider) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) error {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheProvider_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type CacheProvider_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *CacheProvider_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *CacheProvider_Set_Call {
	return &CacheProvider_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *CacheProvider_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *CacheProvider_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *CacheProvider_Set_Call) Return(_a0 error) *CacheProvider_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheProvider_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *CacheProvider_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetJSON provides a mock function with given fields: ctx, key, val, ttl
func (_m *CacheProvider) SetJSON(ctx context.Context, key string, val interface{}, ttl time.Duration) error {
	ret := _m.Called(ctx, key, val, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, val, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheProvider_SetJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetJSON'
type CacheProvider_SetJSON_Call struct {
	*mock.Call
}

// SetJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val interface{}
//   - ttl time.Duration
func (_e *CacheProvider_Expecter) SetJSON(ctx interface{}, key interface{}, val interface{}, ttl interface{}) *CacheProvider_SetJSON_Call {
	return &CacheProvider_SetJSON_Call{Call: _e.mock.On("SetJSON", ctx, key, val, ttl)}
}

func (_c *CacheProvider_SetJSON_Call) Run(run func(ctx context.Context, key string, val interface{}, ttl time.Duration)) *CacheProvider_SetJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *CacheProvider_SetJSON_Call) Return(_a0 error) *CacheProvider_SetJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheProvider_SetJSON_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *CacheProvider_SetJSON_Call {
	_c.Call.Return(run)
	return _c
}

// NewCacheProvider creates a new instance of CacheProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheProvider {
	mock := &CacheProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
